title: Data Science Project
description: Illustrating techniques learnt in class to assess nitrate pollution from agricultural lands to surface water bodies
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
